version: '3'
services:

  php:
    image: php:8.3-fpm
    build:
      context: ./
      dockerfile: docker/Dockerfile
    volumes:
      - '.:/var/www/html'
      - './docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini'
    links:
      - db
    env_file:
      - .env


  nginx:
    image: nginx:latest
    ports:
      - '8082:80'
    volumes:
      - '.:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
    links:
      - php

  db:
    image: postgres
    volumes:
      - './data:/var/lib/postgresql/data'
    ports:
      - '5434:5432'
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}